# SPDX-FileCopyrightText: 2025 INSEE
#
# SPDX-License-Identifier: CC0-1.0

name: Docker build

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'usequarto'
    paths:
      - "./Dockerfile"
      - "./pynsee/*"
      - "./tests/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: inseefrlab/pynsee:latest
